# Generated by Django 3.2.5 on 2021-10-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Setting',
        ),
    ]
